---
title: "CNV Processing"
output: html_notebook
---
2019 CTD Processing for cnv files
First writted by ASL 02 Aug 2019

# Load packages and assign global variables
```{r}
#First written by RPM April 2018
#06 June 2019 updated by RPM

### Load OCE Libraries and Carey Lab ctd functions###
pacman::p_load(oce, ocedata, tidyverse, lubridate)
source("ctd_functions.R") #Load Carey Lab ctd functions
source("CTD_matlab_functions.R") #Load Carey Lab ctd function for creating the glm aed dataset and a file for matlab

#Specify global variables
DATE_TEXT <- "15-Aug-2019" #format should be "01-Aug-2019"
SITE <- "fcr50"
SAMPLER <- ""
MAX_DEPTH <- 9.3 #9.3 for FCR, 11 for BVR




#Advanced customization
REP <- "" #If multiple casts were taken this will be _a, _b, _c, etc. Be sure to include an underscore
AUTO_NAME <- TRUE #If using a nonstandard name format. Must also fill in NAME_OVERRIDE below
NAME_OVERRIDE <- "" #For example, "080119_fcr50"
AUTO_FOLDER <- TRUE #Default is "CTD_CASTS_CSV" if site == "fcr50" and the working directory for all other sites. Enter FALSE here if you would like to save to a different folder (e.g. for MSNs)
CSV_FOLDER_OVERRIDE <- "" #Enter "MSN_CTD_DATA" here for MSN data
```


#Choose the scan number that starts the cast
  -Verify that this starts above 0 dbar, only includes the downcast, and both plots are identical
  -You can ignore the "unrecognized SBE name" warning message
```{r}
SCAN_NUMBER <- 405
ctdTrimmed <- trim_ctd(SCAN_NUMBER, DATE_TEXT, AUTO_NAME, SITE, REP, NAME_OVERRIDE)
```

Everything else should be automated, just run this chunk of code!
```{r}
epic_ctd_function(ctdTrimmed, DATE_TEXT, SITE, SAMPLER, REP, AUTO_NAME, NAME_OVERRIDE, AUTO_FOLDER, CSV_FOLDER_OVERRIDE, MAX_DEPTH)

on = as_datetime(c("2019-06-03 15:57:00","2019-07-08 9:30:00", "2019-08-05 12:45:00")) #July time is estimated based on the time for other sampling. TZ is UTC to match catwalk and current CTD processing
off = as_datetime(c("2019-06-17 15:04:00","2019-07-22 00:00:00", "2019-08-19 00:00:00")) #July date is wrong bc system broke. TZ is UTC to match catwalk and current CTD processing

#Create dataframes and catwalk comparison for the whole season at fcr50
if(SITE == "fcr50"){
  pacman::p_load(tidyverse, zoo, lubridate, rLakeAnalyzer,reshape2,akima,dplyr,gridExtra,grid,colorRamps,RCurl)
  forCatwalkComparison <- fcr_data_wrangling()
  #Compare to catwalk
  ctd_vs_catwalk(forCatwalkComparison,on,off) #This step takes a couple minutes
}
```