---
title: "Catwalk for EDI"
author: "Abby Lewis"
date: "12/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(pacman)
pacman::p_load("RCurl","tidyverse","lubridate")
source("temp_oxy_chla_qaqc.R")
```

```{r}
download.file('https://github.com/CareyLabVT/SCCData/raw/mia-data/Catwalk.csv','Catwalk.csv')

temp_oxy_chla_qaqc('Catwalk.csv',"CAT_MaintenanceLog.txt","Catwalk_final.csv")

catdata <- read.csv("Catwalk_final.csv")
catdata$DateTime<-as.POSIXct(catdata$DateTime,format = "%Y-%m-%d %H:%M:%S")

catdata_published <- catdata[catdata$DateTime<="2018-12-16",]
catdata_published <- catdata_published[!is.na(catdata_published$Flag_All),]
catdata_flag <- catdata[catdata$DateTime>"2018-12-16",]

catdata_flag$Flag_All <- 0
catdata_flag$Flag_DO_1 <- 0
catdata_flag$Flag_DO_5 <- 0
catdata_flag$Flag_DO_9 <- 0
catdata_flag$Flag_Chla <- 0
catdata_flag$Flag_Phyco <- 0
catdata_flag$Flag_TDS <- 0


# now fix the negative DO values
#This generates NA in the flag if DO is na. That is okay it will be fixed later.

clean_start <- as_datetime(c("2018-12-17 11:30:00","2019-02-08 12:50:00","2019-06-17 11:10:00","2019-07-17 11:40:00", "2019-08-12 12:40:00","2019-09-27 12:30:00", "2019-10-07 10:30:00","2019-10-11 12:00:00"))
clean_end <- as_datetime(c("2018-12-17 11:40:00","2019-02-08 13:10:00","2019-06-17 11:20:00","2019-07-17 12:40:00","2019-08-12 12:40:00","2019-09-27 13:00:00","2019-10-07 11:00:00","2019-10-11 13:00:00"))

catdata_flag <- catdata_flag %>%  #RDO at 5m
  mutate(Flag_DO_5 = ifelse(RDO_mgL_5 < 0 | RDOsat_percent_5 < 0, 3, Flag_DO_5),
         RDO_mgL_5 = ifelse(RDO_mgL_5 < 0, 0, RDO_mgL_5),
         RDOsat_percent_5 = ifelse(RDOsat_percent_5 < 0, 0, RDOsat_percent_5),
         Flag_DO_5 = ifelse(is.na(RDO_mgL_5),7,Flag_DO_5),
         
         Flag_DO_9 = ifelse(RDO_mgL_9 < 0 | RDOsat_percent_9 < 0, 3, Flag_DO_9),
         RDO_mgL_9 = ifelse(RDO_mgL_9 < 0, 0, RDO_mgL_9),
         RDOsat_percent_9 = ifelse(RDOsat_percent_9 < 0, 0, RDOsat_percent_9),
         Flag_DO_9 = ifelse(is.na(RDO_mgL_9),7,Flag_DO_9),
         
         Flag_DO_1 = ifelse(EXODO_mgL_1 < 0 | EXODOsat_percent_1 <0, 3, Flag_DO_1),
         EXODO_mgL_1 = ifelse(EXODO_mgL_1 < 0, 0, EXODO_mgL_1),
         EXODOsat_percent_1 = ifelse(EXODOsat_percent_1 <0, 0, EXODOsat_percent_1),
         Flag_DO_1 = ifelse(is.na(EXODO_mgL_1),7,Flag_DO_1))


ADJ_PERIOD = 2*60*60 #amount of time to stabilization after cleaning in seconds

for (i in range(1,length(clean_start))){
  catdata_flag$RDO_mgL_5[catdata_flag$DateTime>clean_start[i]&catdata_flag$DateTime<(clean_end[i]+ADJ_PERIOD)] <- NA
  catdata_flag$RDO_mgL_9[catdata_flag$DateTime>clean_start[i]&catdata_flag$DateTime<clean_end[i]+ADJ_PERIOD] <- NA
  catdata_flag$RDOsat_percent_5[catdata_flag$DateTime>clean_start[i]&catdata_flag$DateTime<clean_end[i]+ADJ_PERIOD] <- NA
  catdata_flag$RDOsat_percent_9[catdata_flag$DateTime>clean_start[i]&catdata_flag$DateTime<clean_end[i]+ADJ_PERIOD] <- NA
  catdata_flag$Flag_DO_5[catdata_flag$DateTime>clean_start[i]&catdata_flag$DateTime<clean_end[i]+ADJ_PERIOD] <- 1
  catdata_flag$Flag_DO_9[catdata_flag$DateTime>clean_start[i]&catdata_flag$DateTime<clean_end[i]+ADJ_PERIOD] <- 1
}


on = as_datetime(c("2019-06-03 15:57:00","2019-07-08 9:30:00", "2019-08-05 12:45:00", "2019-09-02 13:00:00")) #July time is estimated based on the time for other sampling. TZ is UTC to match catwalk and current CTD processing
off = as_datetime(c("2019-06-17 15:04:00","2019-07-22 16:30:00", "2019-08-19 13:00:00"))

################
#Creating a new flag "6" which means the values seemed so suspect that we adjusted them
################


catdata_adj = catdata_flag%>%
  mutate(
     # 5 meters
     Flag_DO_5 = ifelse(DateTime<as_datetime("2019-08-12 12:40:00") & DateTime> as_datetime("2019-08-11 00:00:00"), 6, Flag_DO_5),
     RDO_mgL_5_adjusted = ifelse(DateTime<"2019-08-12 12:40:00" & DateTime> "2019-08-11 00:00:00", 
                                RDO_mgL_5 + sqrt(as.numeric(difftime(DateTime,"2019-08-11 00:00:00", units = "mins")))/30,
                                RDO_mgL_5),
     RDOsat_percent_5_adjusted = ifelse(DateTime<"2019-08-12 12:40:00" & DateTime> "2019-08-11 00:00:00", 
                                RDOsat_percent_5 + sqrt(as.numeric(difftime(DateTime,"2019-08-11 00:00:00", units = "mins")))/30/11.3*100,
                                RDOsat_percent_5),
     Flag_DO_5 = ifelse(DateTime<as_datetime("2019-07-17 11:40:00") & DateTime> as_datetime("2019-07-13 00:00:00"), 5, Flag_DO_5),
     
     #9 meters 
     Flag_DO_9 = ifelse(DateTime<"2019-08-12 12:40:00" & DateTime> "2019-08-05 12:45:00",6, Flag_DO_9),
     RDO_mgL_9_adjusted = ifelse(DateTime<"2019-08-12 12:40:00" & DateTime> "2019-08-05 12:45:00", 
                                RDO_mgL_9 + sqrt(as.numeric(difftime(DateTime,"2019-08-05 12:45:00", units = "mins")))/70,
                                RDO_mgL_9),
     RDOsat_percent_9_adjusted = ifelse(DateTime<"2019-08-12 12:40:00" & DateTime> "2019-08-05 12:45:00", 
                                RDOsat_percent_9 + sqrt(as.numeric(difftime(DateTime,"2019-08-05 12:45:00", units = "mins")))/70/11.3*100,
                                RDOsat_percent_9),
     Flag_DO_9 = ifelse(DateTime<as_datetime("2019-07-17 11:40:00") & DateTime> as_datetime("2019-07-13 00:00:00"), 5, Flag_DO_9),
     Flag_DO_9 = ifelse(DateTime<as_datetime("2019-08-19 13:00:00") & DateTime> as_datetime("2019-08-12 12:40:00"), 5, Flag_DO_9),
     
     # 9 meters september
     Flag_DO_9 = ifelse(DateTime<"2019-09-27 12:30:00" & DateTime> "2019-09-02 13:00:00",6, Flag_DO_9),
     RDO_mgL_9_adjusted = ifelse(DateTime<"2019-09-27 12:30:00" & DateTime> "2019-09-02 13:00:00", 
                                RDO_mgL_9 + as.numeric(difftime(DateTime,"2019-09-02 13:00:00", units = "mins"))/30000,
                                RDO_mgL_9_adjusted),
     RDOsat_percent_9_adjusted = ifelse(DateTime<"2019-09-27 12:30:00" & DateTime> "2019-09-02 13:00:00", 
                                RDOsat_percent_9 + as.numeric(difftime(DateTime,"2019-09-02 13:00:00", units = "mins"))/30000/11.3*100,
                                RDOsat_percent_9_adjusted))




catdata_final <- catdata_published%>%
  full_join(catdata_adj)%>%
  select(Reservoir, Site, DateTime, ThermistorTemp_C_surface, ThermistorTemp_C_1, ThermistorTemp_C_2, ThermistorTemp_C_3, ThermistorTemp_C_4, ThermistorTemp_C_5, ThermistorTemp_C_6, ThermistorTemp_C_7, ThermistorTemp_C_8, ThermistorTemp_C_9, RDO_mgL_5, RDOsat_percent_5, RDOTemp_C_5, RDO_mgL_9, RDOsat_percent_9, RDOTemp_C_9, EXOTemp_C_1, EXOCond_uScm_1, EXOSpCond_uScm_1, EXOTDS_mgL_1, EXODOsat_percent_1, EXODO_mgL_1, EXOChla_RFU_1, EXOChla_ugL_1, EXOBGAPC_RFU_1, EXOBGAPC_ugL_1, EXOfDOM_RFU_1, EXOfDOM_QSU_1, EXO_pressure, EXO_depth, EXO_battery, EXO_cablepower, EXO_wiper, RECORD, CR6_Batt_V, CR6Panel_Temp_C, RDO_mgL_5_adjusted, RDOsat_percent_5_adjusted, RDO_mgL_9_adjusted, RDOsat_percent_9_adjusted, Flag_All, Flag_DO_1, Flag_DO_5, Flag_DO_9, Flag_Chla, Flag_Phyco, Flag_TDS)

catdata_final <- catdata_final[!is.na(catdata_final$Reservoir),]
catdata_final <- catdata_final[year(catdata_final$DateTime)<2020,]

write_csv(catdata_final,"catdata_edited_withDO.csv")
```
